relay_servers:
  # - "ws://universe.nostrich.land/?lang=ja"
  - "wss://relay-jp.nostr.wirednet.jp"
  - "wss://relay.nostr.wirednet.jp"
  - "wss://nostr.wine"
  - "wss://relay.damus.io"
  - "wss://relay.snort.social"
  - "wss://nostr-pub.wellorder.net"
  - "wss://nos.lol"
